### ISSUE TITLE
Seems to work on objects too

### ISSUE THREAD

**Issue by KeitIG** [emn178/js-md5#1]
Hi !

Could you add on the README it works on objects too ? (and it's quite performant)
I was afraid to do a `md5(JSON.stringify(object))` (250ms), but `md5(myobject)` seems to work in 1.5ms.

**Comment by emn178** [comment]
Hi,

It does not support object. I think the md5 result is incorrect.

**Comment by KeitIG** [comment]
Well, I don't know if the md5 hash is correct, but there's an output different for every object I parse. And this was what I was looking to do a deep comparison. But maybe I've done something wrong.

**Comment by KeitIG** [comment]
After working a bit on it, it's true that it "shouldn't work" on objects. I'll turn myself to a simple JSON.stringify, thanks !
