### ISSUE TITLE
Error on IE 10 when using non-string messages

### ISSUE THREAD

**Issue by claudiucismaru** [emn178/js-md5#14]
On IE10, there is no ArrayBuffer.isView() method. As this is called when try to call the md5 function with a blob or anything else than a string, IE 10 reports error of isView not being defined.

As a workaround, a polyfill could be created to add isView() function to ArrayBuffer (should be pretty simple, I made it in several lines of code) or change the code to not call that method, at all.

**Comment by emn178** [comment]
I will check this. Thanks.

**Comment by emn178** [comment]
Added polyfill in v0.6.1. But I have no IE 10 to test this. Please try it. It should work. Thanks.

**Comment by claudiucismaru** [comment]
Apparently seems to work now. Anyway, you can grab IE 10 for testing purposes on a VM from Microsoft, here: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
