### ISSUE TITLE
Size limit

### ISSUE THREAD

**Issue by Loscillo** [emn178/js-md5#15]
Hello,

I'm tried to use your system to checksum big files (3G) and your script doesn't work and stay with loading message. Do you have limited the size on the script or it's a limit of the browser or the system.

Thanks for your answer.

**Comment by emn178** [comment]
seems browser limit the file size. I will survey this issue when I have time.

**Comment by emn178** [comment]
It should work now. Please try again.

**Comment by Loscillo** [comment]
It seems to work properly. Thank you for solving this problem.
