### ISSUE TITLE
Array buffer allocation failure

### ISSUE THREAD

**Issue by rayjennings3rd** [emn178/js-md5#16]
buffer.js:93
    return new ArrayBuffer(size);
           ^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at createUnsafeArrayBuffer (buffer.js:93:12)
    at createUnsafeBuffer (buffer.js:87:25)
    at allocate (buffer.js:291:12)
    at fromObject (buffer.js:372:15)
    at Function.Buffer.from (buffer.js:192:11)
    at new Buffer (buffer.js:158:17)
    at nodeMethod (/root/jam-utils/node_modules/js-md5/src/md5.js:170:48)

Is there an absolute maximum of a data stream that can be computed over?

**Comment by emn178** [comment]
It's ArrayBuffer behavior. Depends on your system. see: https://www.ecma-international.org/ecma-262/6.0/#sec-createbytedatablock
> If it is impossible to create such a Data Block, throw a RangeError exception.

You have to read by steaming if the file is too large.

**Comment by rayjennings3rd** [comment]
Is that an option, to pass in a readable stream? I did not see that in the docs. Something like:

`let hash = md5(rSteam);`

**Comment by emn178** [comment]
something like this
```JavaScript
var hash = md5.create();
var readStream = fs.createReadStream('./large-file');
readStream.on('data', function (chunk) {
  hash.update(chunk);
}).on('end', function () {
  console.log(hash.hex());
});
```

**Comment by rayjennings3rd** [comment]
Okay, I was trying to avoid write the stream out to disk but I think I have a way to do it with http.request() stream. Thanks!
