### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by aajahid** [emn178/js-md5#2]
I was trying to use it in a typescript based project. Does it have typescript support? If not - any easy way to get it working with typescript?

And finally if you have plan to official support typescript?

**Comment by emn178** [comment]
Hi,

Sorry, I don't know how to use TypeScript, but I found this
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/js-md5/md5.d.ts

Maybe you can upgrade it.

**Comment by aajahid** [comment]
Yes. Thats the one I was looking. Thank you very much for your help!
