### ISSUE TITLE
Possible Malware

### ISSUE THREAD

**Issue by EncomCTO** [emn178/js-md5#21]
This is possibly a false positive, but wanted to mention it.  I just ran Malwarebytes on my Mac and it quarantined files from this repo for Adware.  Worth running a quick scan on your code.  

Thanks.

**Comment by emn178** [comment]
which file?

**Comment by EncomCTO** [comment]
It quarantined the whole directory.

**Comment by emn178** [comment]
Dependencies updated. Fixed all npm audit issues.
