### ISSUE TITLE
React native expo doesnt work after update to 0.8.0.

### ISSUE THREAD

**Issue by sergeushenecz** [emn178/js-md5#40]
Hi everyone. After update to 0.8.0 from prev version my react native app stop working. On the build step i got error.

<img width="1564" alt="image" src="https://github.com/emn178/js-md5/assets/7217517/be592061-5129-45bf-94e7-041c9092ec7e">

**Comment by emn178** [comment]
added browser in package.json, please check if it works.

**Comment by sergeushenecz** [comment]
> added browser in package.json, please check if it works.

Yes,  build is succesfully.
