### ISSUE TITLE
Doesn't work correctly in Electron

### ISSUE THREAD

**Issue by simonhamp** [emn178/js-md5#47]
Some NativePHP users are experiencing [this issue](https://github.com/orgs/NativePHP/discussions/345#discussion-7050375) via [Filament](https://github.com/filamentphp/filament/discussions/12388), an open source component library and admin panel solution for Laravel.

It seems that under Electron, [this check returns `true` when it's not expected to](https://qiita.com/nasteng/items/9984175ec505663c2321#%E3%81%AA%E3%82%93%E3%81%A7%E3%83%96%E3%83%A9%E3%82%A6%E3%82%B6%E3%81%A7%E3%81%AF%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%8C%E8%B5%B7%E3%81%8D%E3%81%AA%E3%81%84%E3%81%AE%E3%81%8B):

```
var NODE_JS = !root.JS_MD5_NO_NODE_JS && typeof process === 'object' && process.versions && process.versions.node;
```

Is there something you could do to fix this? Or is there maybe a build option on the Filament side that might help?

**Comment by emn178** [comment]
Try to set `global.JS_MD5_NO_NODE_JS = true` before require js-md5. `global` may have a different name in your environment.

**Comment by simonhamp** [comment]
Thanks! I believe this is working for folks 👍🏼
