### ISSUE TITLE
Secret

### ISSUE THREAD

**Issue by kenanchristian** [emn178/js-md5#6]
Is there a way to use a secret when creating the MD5 hash?

**Comment by emn178** [comment]
Do you mean salt? concat string and hash.
```JavaScript
md5(salt + str);
```
or bytes
```JavaScript
md5.update(salt).update(str).hex();
```

**Comment by kenanchristian** [comment]
Cool, thanks!
Didn't see it this way, because I used another library that take the salt on other argument.

**Comment by AlttiRi** [comment]
I think he talked about HMAC.

And `md5(salt + str);` or `md5.update(salt).update(str).hex();` **are not** the correct implementation of HMAC.

https://en.wikipedia.org/wiki/HMAC

**Comment by AlttiRi** [comment]
https://github.com/blueimp/JavaScript-MD5/blob/ed24666b03e7f3af777da5d487b24fbb6f91b673/js/md5.js#L285

```js
md5("The quick brown fox jumps over the lazy dog", "key"); // "80070713463e7749b90c2dc24911e275"
```

**Comment by AlttiRi** [comment]
But I don't think that is a big problem. MD5 should not be used in cryptographic operations.

Using it, for example, for file naming or for computing file checksum* is OK.

_*when you sure that file is not compromised. (Using MD5 for images or videos is OK, but for executable files does not)_
