### ISSUE TITLE
using webpack problem

### ISSUE THREAD

**Issue by daddybh** [emn178/js-md5#8]
hi , when I use webpack to package my code, it will recognize `js-md5` as node module and compact with a lot of polyfill code. 

Please take a look at this problems, thanks

eg:
![dddd](https://cloud.githubusercontent.com/assets/3275603/22194052/d654da56-e17a-11e6-97b8-229a39698363.png)

**Comment by emn178** [comment]
hi, js-md5 will use Node.js method in Node.js environment. see
https://github.com/emn178/js-md5/blob/master/src/md5.js#L126-L127
If webpack finds that source code includes `require('xxx')`, it will include the dependencies in bundle file.
Sorry, but I can't stop webpack doing this.

If you don't want to include anyway, you can remove the part related to Node.js from source code.

**Comment by emn178** [comment]
I found a way to ignore the dependencies. Set up your webpack config by this.
```JavaScript
var webpack = require('webpack');
module.exports = {
  // ...
  plugins: [
    new webpack.IgnorePlugin(/^crypto$/),
    new webpack.IgnorePlugin(/^buffer$/)
  ]
};
```
Remember to remove if other libraries really need these.

**Comment by daddybh** [comment]
thanks @emn178 , webpack plugins could solve the problem. I guess it's pretty simple to do md5 within nodejs, what do you think make js-md5 a pure front-end lib, :)

**Comment by emn178** [comment]
I make it provides the same interface so that you can write an application run in both front-end and back-end with this library.

**Comment by joshxyzhimself** [comment]
Different syntax for `ignorePlugin` in webpack 5?

https://webpack.js.org/plugins/ignore-plugin/
