### ISSUE TITLE
Different MD5 hash

### ISSUE THREAD

**Issue by KingRider** [emn178/js-md5#9]
Web hashkiller MD5 Hashes
https://hashkiller.co.uk/md5-decrypter.aspx

Result different emn178

Why different? ... correct hashkiller a result

How to make its? help-me

**Comment by emn178** [comment]
Your url is decrypter. of course different.

**Comment by KingRider** [comment]
So i found he is SHA-1, small different md5, but have code million make decrypt =[ ... wordpress need decrypt its. nvm.

**Comment by 277801235** [comment]
It doesn't work on web worker thread?
